### ISSUE TITLE
Tailwind 2 support

### ISSUE THREAD

**Issue by alapini** [dev-warner/react-static-plugin-tailwindcss#1]
The current version of react-static-plugin-tailwindcss does not seem to support Tailwind 2.*
There is a post-css version conflict.
Still working fine with tailwind 1.*

**Comment by codicocodes** [comment]
@alapini Did you end up finding any good solution / workaround for tailwind 2 with react-static?

**Comment by rolandtoth** [comment]
@alapini Any news on this?

**Comment by dev-warner** [comment]
Hey! Sorry for the v.slow replies.  The work around is to follow this guide:

>https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

`react-static` uses `postcss` 7 i believe and the latest `tailwind` version requires `postcss` 8

To resolve this issue:

```bash
yarn remove tailwind
yarn add tailwindcss@npm:@tailwindcss/postcss7-compat
```

I will update the docs with paths for both version 1 and 2 of tailwind.

**Comment by dev-warner** [comment]
PR: now open

https://github.com/dev-warner/react-static-plugin-tailwindcss/pull/2/files
